receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: aws_monitor
    const_labels:
      service: aws-monitor
  
  logging:
    loglevel: info
  
  # Uncomment and configure for your specific backends
  # jaeger:
  #   endpoint: jaeger:14250
  #   tls:
  #     insecure: true
  
  # prometheusremotewrite:
  #   endpoint: "http://prometheus:9090/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]
    
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
  
  extensions: []