receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
  resource/env:
    attributes:
    - key: environment
      value: nimisha-local-mac
      action: upsert

exporters:
  clickhouse:
    endpoint: "tcp://aws-monitor-clickhouse:9000"
    database: "otel"
    logs_table_name: otel_logs
    metrics_table_name: otel_metrics
    username: default
    password: "admin"
    create_schema: true
  
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource/env]
      exporters: [clickhouse]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource/env]
      exporters: [clickhouse]
    
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource/env]
      exporters: [clickhouse]
  
  extensions: []
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://localhost:4318

    logs:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://localhost:4318
    traces:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://localhost:4318